### ISSUE TITLE
Use Yarn to manage bower dependencies?

### ISSUE THREAD

**Issue by lougreenwood** [hugoruscitti/ember-circle-progress#1]
The Yarn package manager (https://yarnpkg.com/en/) can be used to manage both bower & npm dependences.

It also allows Bower dependencies to be stored in `package.json`.

The Bower project are also recommending moving to Yarn from Bower : https://bower.io/blog/

Are there any plans update this project to use Yarn instead?

**Comment by lougreenwood** [comment]
It turns out that jquery-circle-progress now also has a `package.json` file, so it can be added as an npm dependency.

I tried to update the add-on to use the nam dependency, but I ran into some problems with Jquery on my branch (I'm very new to Ember...)

**Comment by hugoruscitti** [comment]
Thanks @lougreenwood !!! i want to update this addon to support npm instead bower, i will try to update it tomorrow, i will write you when i was able to make it works.

**Comment by lougreenwood** [comment]
Cool - have you tried using the plugin with ember FastBoot? Seems it currently has some issues, but that may just be caused by the Bower dependency

**Comment by lougreenwood** [comment]
Morning, FYI - this is the error I get when trying to use the current (Bower-based) version with Fastboot:

```
/app/dist/assets/vendor.js:250
    throw new Error('Could not find module `' + id + '` imported from `' + referrer + '`');
    ^

Error: Could not find module `jquery` imported from `(require)`
    at missingModule (/app/dist/assets/vendor/loader/loader.js:247:1)
    at findModule (/app/dist/assets/vendor/loader/loader.js:258:1)
    at requireModule (/app/dist/assets/vendor/loader/loader.js:24:1)
    at /app/dist/assets/bower_components/jquery-circle-progress/dist/circle-progress.js:18:1
    at /app/dist/assets/bower_components/jquery-circle-progress/dist/circle-progress.js:25:1
    at Script.runInContext (vm.js:74:29)
    at VMSandbox.eval (/app/node_modules/fastboot/src/vm-sandbox.js:14:16)
    at /app/node_modules/fastboot/src/ember-app.js:156:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/app/node_modules/fastboot/src/ember-app.js:153:21)
    at EmberApp.retrieveSandboxedApp (/app/node_modules/fastboot/src/ember-app.js:201:10)
    at new EmberApp (/app/node_modules/fastboot/src/ember-app.js:59:21)
    at FastBoot._buildEmberApp (/app/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/app/node_modules/fastboot/src/index.js:52:10)
    at Worker.buildMiddleware (/app/node_modules/fastboot-app-server/src/worker.js:74:21)
    at Worker.start (/app/node_modules/fastboot-app-server/src/worker.js:48:30)
    at new FastBootAppServer (/app/node_modules/fastboot-app-server/src/fastboot-app-server.js:53:19)
    at Object.<anonymous> (/app/server.js:5:14)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

I'm new to Ember, but maybe this add-on should use Ember's JQuery instance instead of bringing it's own dependency? :)

**Comment by hugoruscitti** [comment]
Hi @lougreenwood !!

I was able to remove the bower dependency and update the package completely.

I don't have experience with fast boot, so i don't try if this addon works on fastboot too. Can you try if it works?

**Comment by lougreenwood** [comment]
Cool - seems to work for me too - thank you.

However FastBoot still isn't happy - I get this error:

```
/Users/Lou/Sites/prog/tmp/broccoli_merge_trees-output_path-Nl42fHzy.tmp/assets/vendor.js:250
    throw new Error('Could not find module `' + id + '` imported from `' + referrer + '`');
    ^

Error: Could not find module `jquery` imported from `(require)`
    at missingModule (/Users/Lou/Sites/prog/tmp/broccoli_merge_trees-output_path-Nl42fHzy.tmp/assets/vendor/loader/loader.js:247:1)
    at findModule (/Users/Lou/Sites/prog/tmp/broccoli_merge_trees-output_path-Nl42fHzy.tmp/assets/vendor/loader/loader.js:258:1)
    at requireModule (/Users/Lou/Sites/prog/tmp/broccoli_merge_trees-output_path-Nl42fHzy.tmp/assets/vendor/loader/loader.js:24:1)
    at /Users/Lou/Sites/prog/tmp/broccoli_merge_trees-output_path-Nl42fHzy.tmp/assets/vendor/circle-progress.js:18:1
    at /Users/Lou/Sites/prog/tmp/broccoli_merge_trees-output_path-Nl42fHzy.tmp/assets/vendor/circle-progress.js:25:1
    at Script.runInContext (vm.js:74:29)
    at VMSandbox.eval (/Users/Lou/Sites/prog/node_modules/fastboot/src/vm-sandbox.js:14:16)
    at /Users/Lou/Sites/prog/node_modules/fastboot/src/ember-app.js:156:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/Users/Lou/Sites/prog/node_modules/fastboot/src/ember-app.js:153:21)
    at EmberApp.retrieveSandboxedApp (/Users/Lou/Sites/prog/node_modules/fastboot/src/ember-app.js:201:10)
    at new EmberApp (/Users/Lou/Sites/prog/node_modules/fastboot/src/ember-app.js:59:21)
    at FastBoot._buildEmberApp (/Users/Lou/Sites/prog/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/Lou/Sites/prog/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/Lou/Sites/prog/node_modules/ember-cli-fastboot/index.js:318:29)
    at Layer.handle [as handle_request] (/Users/Lou/Sites/prog/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Lou/Sites/prog/node_modules/express/lib/router/index.js:317:13)
    at /Users/Lou/Sites/prog/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/Lou/Sites/prog/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/Lou/Sites/prog/node_modules/express/lib/router/index.js:275:10)
    at err (/Users/Lou/Sites/prog/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/Users/Lou/Sites/prog/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatcher (/Users/Lou/Sites/prog/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:39:19)
    at invokeCallback (/Users/Lou/Sites/prog/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:31)
    at /Users/Lou/Sites/prog/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/Users/Lou/Sites/prog/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

You can try to replicate simply by installing FastBoot: `ember install ember-cli-fastboot` - that is how I trigger it.

**Comment by hugoruscitti** [comment]
Oh, i will try to fix it later. Can you open a issue for me? I will check
it soon
